Document: nightshade
Title: Debian nightshade Manual
Author: <insert document author here>
Abstract: This manual describes what nightshade is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nightshade/nightshade.sgml.gz

Format: postscript
Files: /usr/share/doc/nightshade/nightshade.ps.gz

Format: text
Files: /usr/share/doc/nightshade/nightshade.text.gz

Format: HTML
Index: /usr/share/doc/nightshade/html/index.html
Files: /usr/share/doc/nightshade/html/*.html

  
