WidgetClass *class_table[] = {
  (WidgetClass *)(&overrideShellWidgetClass),
  (WidgetClass *)(&transientShellWidgetClass),
  (WidgetClass *)(&topLevelShellWidgetClass),
  (WidgetClass *)(&applicationShellWidgetClass),
  (WidgetClass *)(&xmDialogShellWidgetClass),
  (WidgetClass *)(&xmMenuShellWidgetClass),
  (WidgetClass *)(&xmLabelWidgetClass),
  (WidgetClass *)(&xmLabelGadgetClass),
  (WidgetClass *)(&xmArrowButtonWidgetClass),
  (WidgetClass *)(&xmArrowButtonGadgetClass),
  (WidgetClass *)(&xmPushButtonWidgetClass),
  (WidgetClass *)(&xmPushButtonGadgetClass),
  (WidgetClass *)(&xmToggleButtonWidgetClass),
  (WidgetClass *)(&xmToggleButtonGadgetClass),
  (WidgetClass *)(&xmCascadeButtonWidgetClass),
  (WidgetClass *)(&xmCascadeButtonGadgetClass),
  (WidgetClass *)(&xmSeparatorWidgetClass),
  (WidgetClass *)(&xmSeparatorGadgetClass),
  (WidgetClass *)(&xmDrawnButtonWidgetClass),
  (WidgetClass *)(&xmMenuShellWidgetClass),
  (WidgetClass *)(&xmDrawingAreaWidgetClass),
  (WidgetClass *)(&xmDialogShellWidgetClass),
  (WidgetClass *)(&xmBulletinBoardWidgetClass),
  (WidgetClass *)(&xmCommandWidgetClass),
  (WidgetClass *)(&xmFileSelectionBoxWidgetClass),
  (WidgetClass *)(&xmFormWidgetClass),
  (WidgetClass *)(&xmMessageBoxWidgetClass),
  (WidgetClass *)(&xmSelectionBoxWidgetClass),
  (WidgetClass *)(&xmScrollBarWidgetClass),
  (WidgetClass *)(&xmTextWidgetClass),
  (WidgetClass *)(&xmTextFieldWidgetClass),
  (WidgetClass *)(&xmRowColumnWidgetClass),
  (WidgetClass *)(&xmScaleWidgetClass),
  (WidgetClass *)(&xmFrameWidgetClass),
  (WidgetClass *)(&xmListWidgetClass),
  (WidgetClass *)(&xmMainWindowWidgetClass),
  (WidgetClass *)(&xmScrolledWindowWidgetClass),
  (WidgetClass *)(&xmPanedWindowWidgetClass),
  NULL
};

#define CLASS_TABLE_SIZE 38
