#!/bin/csh -f
#
#  build-core -- build full lisp core.

$argv[1]/lisp/lisp -core $argv[1]/lisp/kernel.core << EOF
(setf (search-list "target:") '("$argv[1]/" "$argv[1]/../src/"))
(load (open "target:tools/worldload.lisp"))
(quit)
EOF
