;;;
;;; **********************************************************************
;;; This code was written as part of the CMU Common Lisp project at
;;; Carnegie Mellon University, and has been placed in the public domain.
;;; If you want to use this code or any part of CMU Common Lisp, please contact
;;; Scott Fahlman or slisp-group@cs.cmu.edu.
;;;
(ext:file-comment
  "$Header: /project/cmucl/cvsroot/src/tools/hemload.lisp,v 1.3 1991/07/29 08:56:59 chiles Exp $")
;;;
;;; **********************************************************************
;;;
;;; This file loads all of Hemlock.
;;;

;;; Stuff to set up the packages Hemlock uses.
;;;
(in-package "HEMLOCK-INTERNALS"
	    :nicknames '("HI")
	    :use '("LISP" "EXTENSIONS" "SYSTEM"))
;;;
(in-package "HEMLOCK"
	    :nicknames '("ED")
	    :use '("LISP" "HEMLOCK-INTERNALS" "EXTENSIONS" "SYSTEM"))
;;;
(in-package "SYSTEM")
(export '(%sp-byte-blt %sp-find-character %sp-find-character-with-attribute
		       %sp-reverse-find-character-with-attribute))
;;;
(in-package "HI")

;; FIX for setup-initial-buffer
(defvar make-buffer-hook ())

;; FIX as in 2006
(pushnew :command-bits *features*)
(pushnew :buffered-lines *features*)

(setf (search-list "ed:") "target:hemlock/")

(defun build-hemlock ()
  (load "ed:struct")
;  (load "ed:struct-ed")
  (load "ed:charmacs")
  (load "ed:key-event")
  (ext::re-initialize-key-events)
  (load "ed:keysym-defs")
  (load "ed:input")
  (load "ed:line")
  (load "ed:ring")
  (load "ed:vars")
  (load "ed:buffer")
  (load "ed:macros")
  (load "ed:interp")
  (load "ed:syntax")
  (load "ed:htext1")
  (load "ed:htext2")
  (load "ed:htext3")
  (load "ed:htext4")
  (load "ed:at-point")
  (load "ed:files")
  (load "ed:parse")
  (load "ed:search1")
  (load "ed:search2")
  (load "ed:table")
  #+clx (load "ed:hunk-draw")
;  (load "ed:bit-stream")
  (load "ed:window")
  (load "ed:screen")
  (load "ed:winimage")
  (load "ed:linimage")
  (load "ed:display")
  (load "ed:termcap")
  (load "ed:rompsite")
  #+clx (load "ed:bit-display")
  (load "ed:tty-disp-rt")
  (load "ed:tty-display")
;  (load "ed:tty-stream")
  (load "ed:pop-up-stream")
  #+clx (load "ed:bit-screen")
  (load "ed:tty-screen")
  (load "ed:cursor")
  (load "ed:font")
  (load "ed:streams")
  (load "ed:hacks")
  (load "ed:main")
  (load "ed:echo")
  (load "ed:echocoms")
  (load "ed:command")
  (load "ed:indent")
  (load "ed:comments")
  (load "ed:morecoms")
  (load "ed:undo")
  (load "ed:killcoms")
  (load "ed:searchcoms")
  (load "ed:filecoms")
  (load "ed:doccoms")
  (load "ed:srccom")
  (load "ed:group")
  (load "ed:fill")
  (load "ed:text")
  (load "ed:lispmode")
  (load "ed:ts-buf")
  (load "ed:ts-stream")
  (load "ed:eval-server")
  (load "ed:lispbuf")
  (load "ed:lispeval")
  (load "ed:spell-rt")
  (load "ed:spell-corr")
  (load "ed:spell-aug")
  (load "ed:spellcoms")
  (load "ed:overwrite")
  (load "ed:abbrev")
  (load "ed:dabbrev")
  (load "ed:icom")
  (load "ed:kbdmac")
  (load "ed:defsyn")
  (load "ed:scribe")
  (load "ed:c")
  (load "ed:pascal")
  (load "ed:shell-script")
  (load "ed:python")
  (load "ed:make")
  (load "ed:m4")
  (load "ed:edit-defs")
  (load "ed:auto-save")
  (load "ed:register")
  #+clx (load "ed:xcoms")
  (load "ed:unixcoms")
  (load "ed:mh")
  (load "ed:highlight")
  (load "ed:dired")
  (load "ed:diredcoms")
  (load "ed:bufed")
  (load "ed:lisp-lib")
  (load "ed:completion")
  (load "ed:shell")
  (load "ed:compile")
  (load "ed:debug")
  (load "ed:netnews")
  (load "ed:parse-scribe")
  (load "ed:info")
  (ed::get-info-directory)
  (load "ed:ginfo")
  (load "ed:csv")
  (load "ed:db")
  (load "ed:calendar")
  (load "ed:sort")
  (load "ed:www")
  (load "ed:outline")
  (load "ed:buildtools")
  (load "ed:bindings"))
